### Numpy Tutorials , Basic Operations

In [63]:
#import Numpy library
import numpy as np

In [64]:
# numpy array 1
A = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
print(A)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [65]:
A = A.reshape(3,5)
print(A)
print('-----------------------------------')
print('Shape of Array A: \n', A.shape)
print('-----------------------------------')
print('DataType of Elements A: \n', A.dtype.name)
print('-----------------------------------')
print('DataType of Array A: \n', type(A))
print('-----------------------------------')
print('Shape of Array A: \n', A.size)
print('-----------------------------------')

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
-----------------------------------
Shape of Array A: 
 (3, 5)
-----------------------------------
DataType of Elements A: 
 int32
-----------------------------------
DataType of Array A: 
 <class 'numpy.ndarray'>
-----------------------------------
Shape of Array A: 
 15
-----------------------------------


In [66]:
# arange([start],stop,[step]) 
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [67]:
# np.zeros((n,m)) returns an n x m matrix that contains zeros
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [68]:
# np.eye() returns an identity matrix with the specified dimensions
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [69]:
# np.ones(x,y,z) returns an matrix with ones
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [70]:
## ADD the elements of matrix.
print('sum of whole Array A: \n', np.sum(A))
print('-----------------------------------')
print('sum of rows of Array A: \n', np.sum(A, axis=1))
print('-----------------------------------')
print('sum of columns of Array A: \n', np.sum(A, axis=0))
print('-----------------------------------')

sum of whole Array A: 
 120
-----------------------------------
sum of rows of Array A: 
 [15 40 65]
-----------------------------------
sum of columns of Array A: 
 [18 21 24 27 30]
-----------------------------------


In [71]:
# random value generation using numpy.
np.random.rand(2,4)

array([[0.41559814, 0.22385092, 0.98884626, 0.16014671],
       [0.25245349, 0.99595971, 0.55410624, 0.9376037 ]])

In [72]:
# np.append() adds elements into the specified array.
print('-----------------------------------')
B = np.arange(1,15,2)
print(B)
print('-----------------------------------')
B = np.append(B,2)
print(B)
print('-----------------------------------')
B = B*2
print(B)


-----------------------------------
[ 1  3  5  7  9 11 13]
-----------------------------------
[ 1  3  5  7  9 11 13  2]
-----------------------------------
[ 2  6 10 14 18 22 26  4]


In [73]:
# Slicing : Array[lowerbound(inclusive): upperbound(exclusive)]
B[2:6]

array([10, 14, 18, 22])